---
- name: Get dynomite version
  shell: dynomite -V
  ignore_errors: true
  changed_when: false
  register: dynomite_exist

- name: Install dynomite
  include_tasks: "install.yml"
  when: '"This is dynomite-{{ dynomite_version }}" not in dynomite_exist.stderr'

- name: Place dynomite config
  copy:
    content: "{{ dynomite_config | to_nice_yaml }}"
    dest: /etc/dynomite/dynomite.yml
  notify: Restart dynomite

- name: Create systemd dynomite
  template:
    src: dynomite.service.j2
    dest: /etc/systemd/system/dynomite.service
    owner: root
    group: root
    mode: 0644
  register: unit

- name: Enable and start
  systemd:
    name: dynomite.service
    state: started
    enabled: true
    daemon_reload: "{{ unit.changed }}"
